[tool.poetry]
name = "project1-gorshkov-s"
version = "0.1.0"
description = ""
authors = ["Sergey Gorshkov <Dantistsjohn@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
